export {
  NEW_VALUE_COUNT,
  INIT_CELLS_COUNT,
  NEW_VALUE_LIST,
  WIN_SCORE,
  GAME_BOARD_WIDTH,
  GAME_BOARD_HEIGHT,
}

const NEW_VALUE_COUNT = 1
const INIT_CELLS_COUNT = 2
const NEW_VALUE_LIST = [2]
const WIN_SCORE = 2048
const GAME_BOARD_WIDTH = 4
const GAME_BOARD_HEIGHT = 4
